apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      run: demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: demo
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: 192.168.0.106:32002/demo:0.2
        name: demo
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
